engines:
  fixme:
    enabled: true
ratings:
  paths:
  - "api/src/main/java/**/*.java"
  - "model/src/main/java/**/*.java"
exclude_paths:
- "**/*.gradle"
- "*.md"
- "api/src/test/java/**/*"
- "model/src/test/java/**/*"
