sudo: false # use container-based infrastructure

language: java
jdk:
  - oraclejdk8 # test against version 1.8

cache:
  directories:
    - '$HOME/.gradle/caches' # cache the gradle cache directory
    - '$HOME/.gradle/wrapper' # cache the gradle wrapper directory
    - '$HOME/.m2/repository' # cache the maven artifacts

before_install:
  - chmod +x gradlew # make gradlew script executable

install:
  - ./gradlew assemble

script:
  - ./gradlew check jacocoTestReport # perform tests and compile jacoco test reports

before_cache:
  - find $HOME/.gradle/caches -name "*.lock" -type f -delete
  
after_script:
  - ./gradlew jacocoRootReport coveralls # collect jacoco test reports from subprojects send them to coveralls
