sudo: false # using container-based infrastructure

language: java
jdk:
  - oraclejdk8 # test against version 1.8

cache:
  directories:
    - '$HOME/.m2/repository' # cache the maven artifacts
    - '$HOME/.gradle/wrapper' # cache the gradle wrapper

before_install:
  - chmod +x gradlew # make script gradlew executable

after_success:
  - ./gradlew jacocoTestReport coveralls # send test report to coveralls