sudo: false # use container-based infrastructure

language: java
jdk:
  - oraclejdk10 # test against version 1.10

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - '$HOME/.gradle/caches' # cache the gradle cache directory
    - '$HOME/.gradle/wrapper' # cache the gradle wrapper directory

notifications:
  slack:
    secure: "UITKekk5L3PSJCkakLT1uVhDfJnJ1bY0NG07lEcAWa4OaMAt8G2bjRYrZZFa7eXFerOe3tamowTznWcZ1LYjSPGoBHO1Yd6wBBFfvpAtVA653jG9gPpGVSD8WmCwgzsR6ohrd8pTMI2cq8qohl3itmcSXwquupE1NCx/eG/66tg="

before_install:
  - chmod +x gradlew # ensure that the gradlew script is executable

install:
  - ./gradlew -version # replaces the default of ./gradlew assemble

script:
  - ./gradlew --continue --stacktrace --profile --scan build
#  - ./gradlew --stacktrace sonarqube jacocoTestReport coveralls
  - ./gradlew --stacktrace jacocoTestReport coveralls

after_success:
#  - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then ./gradlew bintrayUpload; fi;
  - ./gradlew --stacktrace bintrayUpload
# only if branch is 'master' and is not a pull request
  - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then ./gradlew --stacktrace versionEyeUpdate; fi;
