sudo: false # use container-based infrastructure

language: java
jdk:
  - oraclejdk8 # test against version 1.8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - '$HOME/.gradle/caches' # cache the gradle cache directory
    - '$HOME/.gradle/wrapper' # cache the gradle wrapper directory

notifications:
  slack:
    secure: "UITKekk5L3PSJCkakLT1uVhDfJnJ1bY0NG07lEcAWa4OaMAt8G2bjRYrZZFa7eXFerOe3tamowTznWcZ1LYjSPGoBHO1Yd6wBBFfvpAtVA653jG9gPpGVSD8WmCwgzsR6ohrd8pTMI2cq8qohl3itmcSXwquupE1NCx/eG/66tg="

before_install:
  - chmod +x gradlew # ensure that the gradlew script is executable

install: true

script:
  - ./gradlew --continue --stacktrace --profile -Dscan build
  - ./gradlew sonarqube jacocoTestReport coveralls

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then ./gradlew bintrayUpload; fi;
