sudo: false # using container-based infrastructure

language: java
jdk:
  - oraclejdk8 # test against version 1.8

cache:
  directories:
    - '$HOME/.gradle/caches' # cache the gradle cache directory
    - '$HOME/.gradle/wrapper' # cache the gradle wrapper directory
    - '$HOME/.m2/repository' # cache the maven artifacts

before_install:
  - chmod +x gradlew # make script gradlew executable

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - ./gradlew jacocoTestReport coveralls # send test report to coveralls
  
#after_success:
#  - ./gradlew jacocoTestReport coveralls # send test report to coveralls
